Repository FixLog/FixLog_Server, pull requests merged in 2025-05, with the labels that each got.

#20 [FEAT] 북마크 폴더 엔티티 추가
  src/main/java/com/example/FixLog/domain/bookmark/BookmarkFolder.java
  src/main/java/com/example/fixlog/domain/bookmark/Bookmark.java
  src/main/java/com/example/fixlog/domain/bookmark/BookmarkTag.java
  src/main/java/com/example/fixlog/domain/bookmark/BookmarkTagMap.java
  src/main/java/com/example/fixlog/domain/member/Member.java
  src/main/java/com/example/fixlog/domain/post/Post.java
Labels: semin

#18 [FEAT] 회원가입
  src/main/java/com/example/fixlog/config/SecurityConfig.java
  src/main/java/com/example/fixlog/controller/member/MemberController.java
  src/main/java/com/example/fixlog/controller/post/PostController.java
  src/main/java/com/example/fixlog/domain/member/Member.java
  src/main/java/com/example/fixlog/dto/member/DuplicateCheckResponseDto.java
  src/main/java/com/example/fixlog/dto/member/SignupRequestDto.java
  src/main/java/com/example/fixlog/exception/ErrorCode.java
  src/main/java/com/example/fixlog/repository/MemberRepository.java
  src/main/java/com/example/fixlog/repository/bookmark/BookmarkRepository.java
  src/main/java/com/example/fixlog/repository/like/PostLikeRepository.java
  src/main/java/com/example/fixlog/repository/post/PostRepository.java
  src/main/java/com/example/fixlog/service/member/MemberService.java
  src/main/resources/application.properties
Labels: chaewon

#21 [FIX] 게시글 작성 및 메인페이지 수정, 도메인 변수명 수정
  build.gradle
  src/main/java/com/example/FixLog/controller/FollowController.java
  src/main/java/com/example/FixLog/controller/MemberController.java
  src/main/java/com/example/FixLog/controller/PostController.java
  src/main/java/com/example/FixLog/domain/bookmark/BookmarkFolder.java
  src/main/java/com/example/FixLog/mock/TagTestDataInitializer.java
  src/main/java/com/example/FixLog/repository/bookmark/BookmarkFolderRepository.java
  src/main/java/com/example/FixLog/repository/post/PostTagRepository.java
  src/main/java/com/example/FixLog/repository/tag/TagRepository.java
  src/main/java/com/example/FixLog/service/FollowService.java
  src/main/java/com/example/FixLog/service/MemberService.java
  src/main/java/com/example/fixlog/config/SecurityConfig.java
  src/main/java/com/example/fixlog/controller/member/MemberController.java
  src/main/java/com/example/fixlog/domain/bookmark/Bookmark.java
  src/main/java/com/example/fixlog/domain/follow/Follow.java
  src/main/java/com/example/fixlog/domain/fork/Fork.java
  src/main/java/com/example/fixlog/domain/like/PostLike.java
  src/main/java/com/example/fixlog/domain/member/Member.java
  src/main/java/com/example/fixlog/domain/post/Post.java
  src/main/java/com/example/fixlog/domain/post/PostImage.java
  src/main/java/com/example/fixlog/domain/post/PostTag.java
  src/main/java/com/example/fixlog/domain/tag/Tag.java
  src/main/java/com/example/fixlog/domain/tag/TagCategory.java
  src/main/java/com/example/fixlog/dto/post/PostRequestDto.java
  src/main/java/com/example/fixlog/exception/ErrorCode.java
  src/main/java/com/example/fixlog/mock/MemberTestDataInitializer.java
  src/main/java/com/example/fixlog/repository/bookmark/BookmarkRepository.java
  src/main/java/com/example/fixlog/repository/follow/FollowRepository.java
  src/main/java/com/example/fixlog/repository/like/PostLikeRepository.java
  src/main/java/com/example/fixlog/service/PostService.java
  src/main/java/com/example/fixlog/service/member/MemberService.java
Labels: youngseo

#37 [FEAT] 로그인
  build.gradle
  src/main/java/com/example/FixLog/config/JwtAuthenticationFilter.java
  src/main/java/com/example/FixLog/config/SecurityConfig.java
  src/main/java/com/example/FixLog/controller/AuthController.java
  src/main/java/com/example/FixLog/controller/MemberController.java
  src/main/java/com/example/FixLog/domain/member/Member.java
  src/main/java/com/example/FixLog/dto/member/LoginRequestDto.java
  src/main/java/com/example/FixLog/dto/member/LoginResponseDto.java
  src/main/java/com/example/FixLog/dto/member/MemberInfoResponseDto.java
  src/main/java/com/example/FixLog/exception/ErrorCode.java
  src/main/java/com/example/FixLog/mock/BookmarkFolderTestDataInitializer.java
  src/main/java/com/example/FixLog/mock/MemberTestDataInitializer.java
  src/main/java/com/example/FixLog/service/AuthService.java
  src/main/java/com/example/FixLog/service/MemberService.java
  src/main/java/com/example/FixLog/util/JwtUtil.java
  src/main/resources/application.properties
Labels: chaewon

#50 [FEAT] 내가 작성한 글 보기
  src/main/java/com/example/FixLog/controller/FollowController.java
  src/main/java/com/example/FixLog/controller/MypagePostController.java
  src/main/java/com/example/FixLog/domain/post/Post.java
  src/main/java/com/example/FixLog/dto/PageResponseDto.java
  src/main/java/com/example/FixLog/dto/post/MyPostPageResponseDto.java
  src/main/java/com/example/FixLog/mock/PostTestDataInitializer.java
  src/main/java/com/example/FixLog/mock/TagTestDataInitializer.java
  src/main/java/com/example/FixLog/repository/bookmark/BookmarkFolderRepository.java
  src/main/java/com/example/FixLog/repository/fork/ForkRepository.java
  src/main/java/com/example/FixLog/repository/post/PostRepository.java
  src/main/java/com/example/FixLog/service/MypagePostService.java
  src/main/resources/application.properties
Labels: semin

#53 [FEAT] 내가 좋아요한 글 보기
  src/main/java/com/example/FixLog/controller/MypagePostController.java
  src/main/java/com/example/FixLog/repository/like/PostLikeRepository.java
  src/main/java/com/example/FixLog/repository/post/PostRepository.java
  src/main/java/com/example/FixLog/service/MypagePostService.java
Labels: semin

#57 [FIX] 메인페이지, 태그 모아보기 수정
  src/main/java/com/example/FixLog/controller/MainPageController.java
  src/main/java/com/example/FixLog/controller/TagController.java
  src/main/java/com/example/FixLog/service/MainPageService.java
  src/main/java/com/example/FixLog/service/TagService.java
  src/main/resources/application.properties
Labels: youngseo
