Repository FixLog/FixLog_Server, pull requests merged in 2025-06, with the labels that each got.

#63 [FEAT] 회원 정보 수정
  .gitignore
  build.gradle
  src/main/java/com/example/FixLog/FixLogApplication.java
  src/main/java/com/example/FixLog/config/AwsS3Config.java
  src/main/java/com/example/FixLog/config/SecurityConfig.java
  src/main/java/com/example/FixLog/controller/MemberController.java
  src/main/java/com/example/FixLog/controller/MypageMemberController.java
  src/main/java/com/example/FixLog/controller/MypagePostController.java
  src/main/java/com/example/FixLog/domain/member/Member.java
  src/main/java/com/example/FixLog/dto/PresignResponseDto.java
  src/main/java/com/example/FixLog/dto/WithdrawRequestDto.java
  src/main/java/com/example/FixLog/dto/member/LoginResponseDto.java
  src/main/java/com/example/FixLog/dto/member/MemberInfoResponseDto.java
  src/main/java/com/example/FixLog/dto/member/ProfilePreviewResponseDto.java
  src/main/java/com/example/FixLog/dto/member/edit/EditBioRequestDto.java
  src/main/java/com/example/FixLog/dto/member/edit/EditNicknameRequestDto.java
  src/main/java/com/example/FixLog/dto/member/edit/EditPasswordRequestDto.java
  src/main/java/com/example/FixLog/dto/member/edit/EditProfileImageRequestDto.java
  src/main/java/com/example/FixLog/exception/ErrorCode.java
  src/main/java/com/example/FixLog/service/AuthService.java
  src/main/java/com/example/FixLog/service/MemberService.java
  src/main/java/com/example/FixLog/service/MypagePostService.java
  src/main/java/com/example/FixLog/service/S3Service.java
  src/main/java/com/example/FixLog/util/DefaultImage.java
  src/main/java/com/example/FixLog/util/DefaultText.java
  src/main/resources/application.properties
Labels: chaewon

#66 [FEAT] 검색 및 검색 결과 페이지
  .gitignore
  build.gradle
  src/main/generated/com/example/FixLog/domain/bookmark/QBookmark.java
  src/main/generated/com/example/FixLog/domain/bookmark/QBookmarkFolder.java
  src/main/generated/com/example/FixLog/domain/follow/QFollow.java
  src/main/generated/com/example/FixLog/domain/fork/QFork.java
  src/main/generated/com/example/FixLog/domain/like/QPostLike.java
  src/main/generated/com/example/FixLog/domain/member/QMember.java
  src/main/generated/com/example/FixLog/domain/post/QPost.java
  src/main/generated/com/example/FixLog/domain/post/QPostTag.java
  src/main/generated/com/example/FixLog/domain/tag/QTag.java
  src/main/generated/com/example/FixLog/tset/QTestMember.java
  src/main/java/com/example/FixLog/config/QuerydslConfig.java
  src/main/java/com/example/FixLog/config/SecurityConfig.java
  src/main/java/com/example/FixLog/controller/SearchController.java
  src/main/java/com/example/FixLog/dto/search/SearchPostDto.java
  src/main/java/com/example/FixLog/dto/search/SearchRequestDto.java
  src/main/java/com/example/FixLog/mock/PostMockDataInitializer.java
  src/main/java/com/example/FixLog/mock/TagMockDataInitializer.java
  src/main/java/com/example/FixLog/repository/post/PostRepository.java
  src/main/java/com/example/FixLog/repository/post/PostRepositoryCustom.java
  src/main/java/com/example/FixLog/repository/post/PostRepositoryImpl.java
  src/main/java/com/example/FixLog/service/AuthService.java
  src/main/java/com/example/FixLog/service/MemberService.java
  src/main/java/com/example/FixLog/service/SearchService.java
  src/main/java/com/example/FixLog/service/impl/SearchServiceImpl.java
  src/main/resources/application.properties
Labels: chaewon

#67 [CHORE] Swagger 설정 초기 세팅
  .gitignore
  build.gradle
  src/main/java/com/example/FixLog/config/SecurityConfig.java
  src/main/java/com/example/FixLog/config/SwaggerConfig.java
  src/main/java/com/example/FixLog/controller/FollowController.java
  src/main/java/com/example/FixLog/controller/MemberController.java
  src/main/java/com/example/FixLog/controller/MypageMemberController.java
  src/main/java/com/example/FixLog/controller/MypagePostController.java
  src/main/java/com/example/FixLog/controller/RedirectController.java
  src/main/resources/application.properties
Labels: chaewon

#80 [FIX] 글 작성하기, 메인페이지
  src/main/java/com/example/FixLog/controller/PostController.java
  src/main/java/com/example/FixLog/service/PostService.java
Labels: youngseo

#82 [FIX] s3 권한 점검 및 프로필 사진 수정
  src/main/java/com/example/FixLog/config/SecurityConfig.java
  src/main/java/com/example/FixLog/controller/MypageMemberController.java
  src/main/java/com/example/FixLog/dto/s3/PresignedUploadResponseDto.java
  src/main/java/com/example/FixLog/service/MainPageService.java
  src/main/java/com/example/FixLog/service/PostService.java
  src/main/java/com/example/FixLog/service/S3Service.java
  src/main/java/com/example/FixLog/util/DefaultImage.java
Labels: chaewon

#87 [FIX] 로그아웃, 회원탈퇴 수정
  src/main/java/com/example/FixLog/controller/AuthController.java
  src/main/java/com/example/FixLog/exception/ErrorCode.java
  src/main/java/com/example/FixLog/service/AuthService.java
Labels: chaewon

#89 [FEAT] 작성자 북마크, 좋아요 보기 추가
  src/main/java/com/example/FixLog/dto/post/MyPostPageResponseDto.java
Labels: semin

#94 [FEAT] 게시글 수정하기
  src/main/java/com/example/FixLog/config/WebConfig.java
  src/main/java/com/example/FixLog/controller/PostController.java
  src/main/java/com/example/FixLog/domain/post/Post.java
  src/main/java/com/example/FixLog/dto/post/NewPostRequestDto.java
  src/main/java/com/example/FixLog/exception/ErrorCode.java
  src/main/java/com/example/FixLog/service/PostService.java
Labels: youngseo

#97 [FIX] 기본 이미지 설정
  src/main/java/com/example/FixLog/dto/post/MyPostPageResponseDto.java
Labels: semin

#104 [FIX] : 데이터 타입, 목업데이터
  src/main/java/com/example/FixLog/domain/post/Post.java
  src/main/java/com/example/FixLog/domain/tag/Tag.java
  src/main/java/com/example/FixLog/dto/main/MainPagePostResponseDto.java
  src/main/java/com/example/FixLog/mock/PostMockDataInitializer.java
  src/main/java/com/example/FixLog/service/MainPageService.java
  src/main/resources/application.properties
Labels: youngseo

#115 [FEAT] 팔로워/팔로잉 목록 프로필 이미지 추가
  src/main/java/com/example/FixLog/dto/follow/response/FollowerListResponseDto.java
  src/main/java/com/example/FixLog/dto/follow/response/FollowingListResponseDto.java
  src/main/java/com/example/FixLog/service/FollowService.java
  src/main/resources/application.properties
Labels: semin
